Home work PR
GlebLudis/weather-forecast pull request #1
Opened 2021-06-07 13:41 UTC by GlebLudis

2021-06-11 20:13 UTC, AntiHero requested changes

2021-06-11 20:13 UTC, AntiHero commented on .github/workflows/deploy-gh-pages.yml
> +      - master
поправить деплой

2021-06-11 20:13 UTC, AntiHero commented on src/app.js
> +  const firstReq = await firstRequest();
убрать неиспользуемые переменные/импорты по всем модулям

2021-06-11 20:13 UTC, AntiHero commented on src/firstRequest.js
> +  console.log(data);
почистить консоль логи

2021-06-11 20:13 UTC, AntiHero commented on src/firstRequest.js
> +  const newKey = `unGTODaBI2fnVlu7XPcaeSj5ndG28d5k`;
посмотреть на повторяющийся код/переменные, вынести, перменные назвать в CAMEL_CASE нотации

2021-06-11 20:13 UTC, AntiHero commented on src/firstRequest.js
> +  document.querySelector(".map").innerHTML = "";
к слову, если первоначально элементы пустые, то и при обращении к ним .innerHTML будет уже пустой строкой

2021-06-11 20:13 UTC, AntiHero commented on src/getCity.test.js
> +    await expect(data).toBe("Moscow");
подумать ещё раз на await перед expect. почитать доку про тестирование асинхронного кода

2021-06-11 20:13 UTC, AntiHero commented on src/storage.test.js
> +  afterEach(() => {
вынести повторяющийся код наверх

2021-06-11 20:13 UTC, AntiHero commented on src/userWeather.test.js
> +    json: () =>
если ты не проверяешь (не использузешь) все данные в своей фэйковой возвращаемой дате, то и не надо её писать, можешь создавать объекты меньше, только с нужными полями, которые используются в коде и в тестах

2021-06-15 08:37 UTC, GlebLudis commented on src/userWeather.test.js
> +    json: () =>
+

2021-06-15 08:37 UTC, GlebLudis commented on src/storage.test.js
> +  afterEach(() => {
+

2021-06-15 11:09 UTC, AntiHero requested changes

2021-06-15 11:09 UTC, AntiHero commented on src/firstRequest.test.js
> +        main: {
нужно ли тебе столько данных указывать? твои функции их все используют?

2021-06-15 11:09 UTC, AntiHero commented on src/getCity.test.js
> +    await expect(data).toBe("Moscow");
почему await перед expect не убрал?

2021-06-15 11:09 UTC, AntiHero commented on src/getWeather.js
> +  const apiKey = "20a60a7e129c650ce2044325518adef8";
если код повторяется есть смысл вынести его в отдельные переменные

2021-06-15 11:09 UTC, AntiHero commented on src/getWeather.test.js
> +    await expect(response).toEqual({ statusText: "OK" });
ещё раз про await

2021-06-15 11:41 UTC, GlebLudis commented on src/firstRequest.test.js
> +        main: {
исправил

2021-06-15 12:45 UTC, merged